services:
  - type: web
    name: izi-contador-backend
    plan: free
    region: ohio
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GOOGLE_CREDENTIALS 
        sync: false

  - type: static_site
    name: izi-contador-frontend
    plan: free
    region: ohio
    env: static
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
