/// <reference types="nativewind/types" />

declare module '*.css' {
  const content: unknown;
  export default content;
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.